export const positions = [
  {
    slug: "operations-lead",
    title: "Event Operations Lead",
    division: "operations",
    signal: "On-Ground Management",
    summary: "Oversee tournament logistics, ground scheduling, player check-ins, and venue management for physical & esports meets.",
  },
  {
    slug: "tournament-director",
    title: "Esports Tournament Director",
    division: "esports",
    signal: "Bracket Systems",
    summary: "Manage tournament brackets, match refereeing, rule enforcement, and match lobby coordination across esports titles.",
  },
  {
    slug: "esports-caster",
    title: "Esports Caster & Host",
    division: "esports",
    signal: "Live Broadcasting",
    summary: "Deliver energetic live play-by-play commentary, pre-match analysis, and player interviews on YouTube & Twitch.",
  },
  {
    slug: "creative-lead",
    title: "Creative & Design Lead",
    division: "creative",
    signal: "Visual Identity",
    summary: "Design official tournament banners, social media posters, team jerseys, motion graphics, and video highlights.",
  },
  {
    slug: "web-developer",
    title: "Fullstack Web Developer",
    division: "technology",
    signal: "Digital Platform",
    summary: "Build registration portals, real-time leaderboard systems, live scorebugs, and internal club automation.",
  },
  {
    slug: "sports-coordinator",
    title: "Athletics & Sports Coordinator",
    division: "operations",
    signal: "Field Athletics",
    summary: "Coordinate team selection, practice sessions, equipment management, and match fixtures for track & field sports.",
  },
  {
    slug: "media-lead",
    title: "Media & PR Manager",
    division: "creative",
    signal: "Social Outreach",
    summary: "Manage official social media channels, press releases, sponsor engagement, and campus promotional campaigns.",
  },
  {
    slug: "tech-infrastructure",
    title: "LAN Systems & Network Engineer",
    division: "technology",
    signal: "Infrastructure",
    summary: "Set up high-speed LAN servers, gaming rigs, low-latency streaming encoders, and audio/video broadcasting hardware.",
  },
];
